# Generated by Django 2.0.5 on 2018-12-20 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('arts_humanities', 'Arts and Humanities'), ('business', 'Business'), ('computer_science', 'Computer Science'), ('health_fitness', 'Health and Fitness'), ('languages', 'Languages'), ('math_logic', 'Math and Logic'), ('music', 'Music'), ('personal_developement', 'Personal Developement')], max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('isFeatured', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('preview_video', models.FileField(blank=True, upload_to='preview_videos')),
                ('preview_video_format', models.CharField(choices=[('video/mp4', 'MP4'), ('video/webm', 'WebM'), ('video/ogg', 'Ogg')], default='video/webm', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='learnify.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, upload_to='course_videos')),
                ('video_format', models.CharField(choices=[('video/mp4', 'MP4'), ('video/webm', 'WebM'), ('video/ogg', 'Ogg')], default='video/webm', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order_number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='learnify.Course')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learnify.UserProfile'),
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learnify.Course'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='learnify.UserProfile'),
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='learnify.UserProfile'),
        ),
    ]
